### ISSUE TITLE
Href link is not working

### ISSUE THREAD

**Issue by ABINASH56** [flutter/flutter_markdown#140] opened 2019-10-30 05:43 UTC
href links are not working. It should take me to a browser but It is not reacting from any angle.

PLEASE SOLVE THIS ISSUE

**Comment by avioli** [comment] 2019-10-31 23:13
In what context?

**Comment by ABINASH56** [comment] 2019-11-04 09:45
> In what context?

 href link looks like ordinary link.Whenever I click on that link it stays static.

**Comment by KagurazakaHanabi** [comment] 2019-11-04 09:46
Show some code please

**Comment by furaiev** [comment] 2019-12-18 13:43
@ABINASH56 
Link can't be just opened in Flutter, for doing it you need an additional plugin (e.g. https://pub.dev/packages/flutter_webview_plugin)

Markdown can only return you a url that can be used further.

Something like:
`body: new Markdown(data: markdownData, onTapLink: print)`
Print you should replace with your logic.

**Comment by avioli** [comment] 2019-12-18 13:50
Of course. It is up to you to manage that. There are too many solutions and none are provided by flutter core to be bundled with this plugin. That is the point of having a plugins system.

Do you want me to point you to a plugin you could use?

[url_launcher](https://pub.dev/packages/url_launcher) is such a plugin and its `launch` function works great with standard https links. Married with `canLaunch` function from the same package you could let the system dictate what schemes it can and can’t handle.

**Comment by bruckmatthew** [comment] 2020-01-11 09:11
I'm on flutter web. This is being wrapped in a ListView, hence the MarkdownBody. The links style is changing (going to blue) but they're not tappable. That is, im not seeing the url being pringted to the terminal. Am I missing something?
```
MarkdownBody(
  data:  """[Google's Homepage][Google]
[inline-style](https://www.google.com)
[reference-style][Google]
<https://www.google.com> """,
  selectable: true,
  onTapLink: print,
), 
```

**Comment by AndroidNils** [comment] 2020-03-06 20:35
Maybe it's caused by this issue: https://github.com/flutter/flutter/issues/43494

**Comment by AndroidNils** [comment] 2020-07-12 15:25
Ticket flutter/flutter#43494 is closed and 
```
Markdown(
  selectable: true,
  onTapLink: (it) => launch(it),
  ....
)
```
is now working 🙂

We can close this ticket 👍

**Comment by SwissCheese5** [comment] 2020-11-17 16:37
Can confirm, this works now!

**Comment by mjordan56** [comment] 2021-01-29 05:31
@domesticmouse It looks like nisreichardt and SwissCheese5 both have confirmed this issue has been fixed.

**Closed** 2021-01-29 21:00 UTC
