### ISSUE TITLE
Can't use flutter markdown version 0.3.1

### ISSUE THREAD

**Issue by steve28100** [flutter/flutter_markdown#159] opened 2019-11-27 02:31 UTC
Guys there is error in version 0.3.1, I can't run the project.

> Analysis of lib/src/style_sheet.dart failed with 17 errors, including:
> 
> line 123 col 33: Invalid constant value.
> 
> line 123 col 49: The getter 'link' isn't defined for the class 'CupertinoColors'.
> 
> line 126 col 42: The getter 'systemGrey6' isn't defined for the class 'CupertinoColors'.
> 
> line 168 col 59: The getter 'separator' isn't defined for the class 'CupertinoColors'.
> 
> line 171 col 66: The getter 'systemGrey6' isn't defined for the class 'CupertinoColors'.
> 
> Analysis of lib/src/_functions_web.dart failed with 2 errors:
> 
> line 5 col 8: Target of URI doesn't exist: 'dart:html'.
> 
> line 48 col 32: Undefined name 'window'.

Please help, thanks.

**Comment by KagurazakaHanabi** [comment] 2019-11-27 02:54
Duplicate of #156

**Comment by domesticmouse** [comment] 2019-11-27 03:31
My bad, I didn't test this release in stable. I'm pushing v0.3.2 that explicitly states the minimum supported Flutter version is 1.10.7, but I can't fix the published v0.3.1 as pub.dev is immutable. I'll update the Travis test scripts to always test on stable flutter after the next stable release so we don't repeat this mistake.

**Closed** 2019-11-27 03:32 UTC

**Comment by domesticmouse** [comment] 2019-11-27 03:33
For a temporary workaround, you can pin your dependency on `flutter_markdown` to v0.3.0 until you can update your Flutter past 1.10.7. Flutter beta is currently 1.11.0, for reference.
