### ISSUE TITLE
'Bold' has a strange bug

### ISSUE THREAD

**Issue by woodstream** [flutter/flutter_markdown#186] opened 2020-02-09 07:10 UTC
1. When rendering this content, it work well:
```
**设计价值的实现方案。**
```
and the result  like this:
>**设计价值的实现方案。**

2. But when rendering this content, it can not work:
```
**设计价值的实现方案。**test
```
and the result like this:
>\**设计价值的实现方案。\**test

3. And when I remove the punctuation and render again, it work well:
```
**设计价值的实现方案**test
```

**Comment by mjordan56** [comment] 2020-07-25 19:30
This was an interesting issue to investigate. After reading section [**6.4 Emphasis and strong emphasis**](https://github.github.com/gfm/#emphasis-and-strong-emphasis) in the [GitHub Flavored Markdown Spec](https://github.github.com/gfm/) and doing some tests of my own, this is expected behavior and not a bug.

Here's why. Section 6.4 defines 17 rules that define emphasis and strong emphasis. The case you've specified involves the behavior of closing strong emphasis. Rule 7 states "A double ** can close strong emphasis iff it is part of a right-flanking delimiter run."

Okay, so what is a right-flanking delimiter run? The specification defines a right-flanking delimiter run as "a delimiter run that is (1) not preceded by Unicode whitespace, and either (2a) not preceded by a punctuation character, or (2b) preceded by a punctuation character and followed by Unicode whitespace or a punctuation character. For purposes of this definition, the beginning and the end of the line count as Unicode whitespace."

The way I interpreted this definition is that in your first example, it works because 2b is true, the right-flanking delimiter run is preceded by a punctuation character and followed by an end-of-line character. Your second example invokes 2a and is now considered an invalid right-flanking delimiter run because it is preceded by a punctuation character but doesn't satisfy 2b. And finally, your third example satisfies 2a in that there is not a preceding punctuation character.

Following these definitions and rules, you'll find that the following cases work because the right-flanking delimiter run is followed with a punctuation character in the first instance and whitespace in the latter case.

```
**设计价值的实现方案。**。test
**设计价值的实现方案。** test
```

**Comment by domesticmouse** [comment] 2020-07-27 09:22
Closing this out. If you still believe this is an issue, please re-open at https://github.com/dart-lang/markdown as this is a parser issue. Thanks!

**Closed** 2020-07-27 09:23 UTC
