### ISSUE TITLE
Italic style inside one word (without spaces)

### ISSUE THREAD

**Issue by comerc** [flutter/flutter_markdown#237] opened 2020-06-22 15:08 UTC
Expected example:

```dart
MarkdownBody(data: '_Word_'));
```

Result:

![Снимок экрана от 2020-06-22 18-05-14](https://user-images.githubusercontent.com/1025241/85303301-f83ac180-b4b2-11ea-8023-8cee564f2a97.png)

Bug Example: 

```dart
MarkdownBody(data: 'W_or_d'));
```

Result:

![Снимок экрана от 2020-06-22 18-02-40](https://user-images.githubusercontent.com/1025241/85303089-b873da00-b4b2-11ea-8feb-8dd3267ff241.png)

**Comment by mjordan56** [comment] 2020-07-25 18:19
This is not a bug. The [GitHub Flavored Markdown Spec](https://github.github.com/gfm) states that "_Emphasis with _ is not allowed inside words_" and provides examples [369](https://github.github.com/gfm/#example-369), [370](https://github.github.com/gfm/#example-370), and [371](https://github.github.com/gfm/#example-371).

If you want to get intraword emphasis you need to use "*". See "_Intraword emphasis with * is permitted" examples [364](https://github.github.com/gfm/#example-364) and [365](https://github.github.com/gfm/#example-365).

I tried your example replacing _ with * and proved the output was as expected.

```
MarkdownBody(data: 'W*or*d');
```

Produces the correct output:

<img width="100" alt="Screen Shot 2020-07-25 at 12 18 49 PM" src="https://user-images.githubusercontent.com/6308118/88463587-0ba1c980-ce71-11ea-9de7-94c2d906a622.png">

**Comment by domesticmouse** [comment] 2020-07-27 09:24
Closing this out. If you still believe this is an issue, please re-open on https://github.com/dart-lang/markdown issue tracker. Thanks!

**Closed by domesticmouse** 2020-07-27 09:24 UTC
