### ISSUE TITLE
Avoid horizontal scrolling

### ISSUE THREAD

**Issue by enricobenedos** [flutter/flutter_markdown#184] opened 2020-02-07 14:53 UTC
Good morning,
with the latest version of the package the text is not wrapped but it is horizontally scrollable.
Before
![image](https://user-images.githubusercontent.com/12233746/74039271-d5a38280-49c1-11ea-9e8c-429a6349ec25.png)
Then 
![image](https://user-images.githubusercontent.com/12233746/74039287-dc31fa00-49c1-11ea-86f8-ecf391a6f311.png)
Is it possible to force text wrapping?

**Comment by mjordan56** [comment] 2020-07-26 23:08
@enricobenedos are you still seeing the behavior you reported? I tried reproducing the bug you described but I get the text wrap behavior you show in your before example. Here's my test code:

```
  final String _data = '''## [0.20.1] Unreleased
  ### Fixed

  * Fixed a bug that crash KPI page if user
  select a days span different from 7. The fix will be removed at
  least we are able to dynamically rewrite the linear chart.
  ''';

  @override
  Widget build(BuildContext context) {
    return Markdown(
      data: _data,
    );
  }
```

Which produced this output:

<img width="368" alt="Screen Shot 2020-07-26 at 5 02 01 PM" src="https://user-images.githubusercontent.com/6308118/88491666-c4dfcc80-cf61-11ea-93e5-4df83fd0510a.png">

There have been changes to the code since you submitted your issue that could have fixed the problem.

BTW, you can set the wrap alignment behavior of block items by setting the WrapAlignment parameter for specific block items in the [MarkdownStyleSheet](https://pub.dev/documentation/flutter_markdown/latest/flutter_markdown/MarkdownStyleSheet-class.html).

**Comment by domesticmouse** [comment] 2020-08-28 20:32
Closing out. If you believe this is still an issue, please comment and I will re-open.

**Closed by domesticmouse** 2020-08-28 20:32 UTC

**Comment by enricobenedos** [comment] 2020-08-31 12:01
Sorry guys for the delay, I will check it as soon as possible due to some issues on my app that I need to solve before this one. Thanks
